<?php

namespace Modules\UserRoles\Database\Seeders;

use Illuminate\Database\Seeder;

class ValidationRulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
    }
    public function run123()
    {


        \DB::table('validation_rules')->delete();

        \DB::table('validation_rules')->insert(array(
            0 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be yes, on, 1, or true. This is useful for validating "Terms of Service" acceptance.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b41',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'accepted',
                'rule_group' => 'Radio-Checkbox-Select-Dropdown',
                'title' => 'accepted',
                'updated_at' => NULL,
            ),
            1 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be a value preceding the given date. The dates will be passed into the PHP strtotime function. In addition, like the after rule, the name of another field under validation may be supplied as the value of date.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b410',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '1',
                'rule' => 'before',
                'rule_group' => 'Date & Time-Date-Time-Month-Day-Year',
                'title' => 'before:date',
                'updated_at' => NULL,
            ),
            2 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be a value preceding or equal to the given date. The dates will be passed into the PHP strtotime function. In addition, like the after rule, the name of another field under validation may be supplied as the value of date.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b411',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '1',
                'rule' => 'before_or_equal',
                'rule_group' => 'Date & Time-Date-Time-Month-Day-Year',
                'title' => 'before_or_equal:date',
                'updated_at' => NULL,
            ),
            3 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must have a size between the given min and max.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b412',
                'is_active' => 0,
                'is_range' => 1,
                'is_related_to_other_field' => 0,
                'num_params' => '2',
                'rule' => 'between',
                'rule_group' => 'Number',
                'title' => 'between:min,max',
                'updated_at' => NULL,
            ),
            4 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be able to be cast as a boolean. Accepted input are true, false, 1, 0, "1", and "0".',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b413',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'boolean',
                'rule_group' => 'Radio-Checkbox-Select-Dropdown',
                'title' => 'boolean',
                'updated_at' => NULL,
            ),
            5 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must have a matching field of foo_confirmation. For example, if the field under validation is password, a matching password_confirmation field must be present in the input.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b414',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => '0',
                'rule' => 'confirmed',
                'rule_group' => NULL,
                'title' => 'confirmed',
                'updated_at' => NULL,
            ),
            6 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be a valid, non-relative date according to the strtotime PHP function.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b415',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'date',
                'rule_group' => 'Date & Time-Date-Time-Month-Day-Year',
                'title' => 'date',
                'updated_at' => NULL,
            ),
            7 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be equal to the given date. The dates will be passed into the PHP strtotime function.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b416',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '1',
                'rule' => 'date_equals',
                'rule_group' => 'Date & Time-Date-Time-Month-Day-Year',
                'title' => 'date_equals:date',
                'updated_at' => NULL,
            ),
            8 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must match the given format. You should use either date or date_format when validating a field, not both. This validation rule supports all formats supported by PHP\'s DateTime class.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b417',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '1',
                'rule' => 'date_format',
                'rule_group' => 'Date & Time-Date-Time-Month-Day-Year',
                'title' => 'date_format:format',
                'updated_at' => NULL,
            ),
            9 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must have a different value than field.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b418',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => '1',
                'rule' => 'different',
                'rule_group' => NULL,
                'title' => 'different:field',
                'updated_at' => NULL,
            ),
            10 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be numeric and must have an exact length of value.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b419',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '1',
                'rule' => 'digits',
                'rule_group' => 'Number',
                'title' => 'digits:value',
                'updated_at' => NULL,
            ),
            11 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must have a valid A or AAAA record according to the dns_get_record PHP function. The hostname of the provided URL is extracted using the parse_url PHP function before being passed to dns_get_record.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b42',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'active_url',
                'rule_group' => 'URL',
                'title' => 'active_url',
                'updated_at' => NULL,
            ),
            12 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be numeric and must have a length between the given min and max.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b420',
                'is_active' => 0,
                'is_range' => 1,
                'is_related_to_other_field' => 0,
                'num_params' => '2',
                'rule' => 'digits_between',
                'rule_group' => 'Number',
                'title' => 'digits_between:min,max',
                'updated_at' => NULL,
            ),
            13 =>
            array(
                'created_at' => NULL,
                'description' => 'The file under validation must be an image meeting the dimension constraints as specified by the rule\'s parameters',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b421',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'dimensions',
                'rule_group' => 'Upload-File',
                'title' => 'dimensions',
                'updated_at' => NULL,
            ),
            14 =>
            array(
                'created_at' => NULL,
                'description' => 'When working with arrays, the field under validation must not have any duplicate',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b422',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'distinct',
                'rule_group' => NULL,
                'title' => 'distinct',
                'updated_at' => NULL,
            ),
            15 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be formatted as an e-mail address.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b423',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'email',
                'rule_group' => 'Text-Textarea-Email',
                'title' => 'email',
                'updated_at' => NULL,
            ),
            16 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must end with one of the given values.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b424',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => 'unlimited',
                'rule' => 'ends_with',
                'rule_group' => NULL,
                'title' => 'ends_with:foo,bar,...',
                'updated_at' => NULL,
            ),
            17 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation will be excluded from the request data returned by the validate and validated methods if the anotherfield field is equal to value.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b425',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => '2',
                'rule' => 'exclude_if',
                'rule_group' => NULL,
                'title' => 'exclude_if:anotherfield,value',
                'updated_at' => NULL,
            ),
            18 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation will be excluded from the request data returned by the validate and validated methods unless anotherfield\'s field is equal to value.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b426',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => '2',
                'rule' => 'exclude_unless',
                'rule_group' => NULL,
                'title' => 'exclude_unless:anotherfield,value',
                'updated_at' => NULL,
            ),
            19 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must exist on a given database table.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b427',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '2',
                'rule' => 'exists
',
                'rule_group' => NULL,
                'title' => 'exists:table,column
',
                'updated_at' => NULL,
            ),
            20 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be a successfully uploaded file.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b428',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'file',
                'rule_group' => 'Upload-File',
                'title' => 'file',
                'updated_at' => NULL,
            ),
            21 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must not be empty when it is present.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b429',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'filled',
                'rule_group' => 'Text-Textarea-Email-Number-Date & Time-Date-Time-Month-Day-Year-URL',
                'title' => 'filled',
                'updated_at' => NULL,
            ),
            22 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be a value after a given date. The dates will be passed into the strtotime PHP function:',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b43',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '1',
                'rule' => 'after',
                'rule_group' => 'Date & Time-Date-Time-Month-Day-Year',
                'title' => 'after:date',
                'updated_at' => NULL,
            ),
            23 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be greater than the given field. The two fields must be of the same type. Strings, numerics, arrays, and files are evaluated using the same conventions as the size rule.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b430',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => '1',
                'rule' => 'gt',
                'rule_group' => 'Number',
                'title' => 'gt:field',
                'updated_at' => NULL,
            ),
            24 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be greater than or equal to the given field. The two fields must be of the same type. Strings, numerics, arrays, and files are evaluated using the same conventions as the size rule.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b431',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => '1',
                'rule' => 'gte',
                'rule_group' => 'Number',
                'title' => 'gte:field',
                'updated_at' => NULL,
            ),
            25 =>
            array(
                'created_at' => NULL,
                'description' => 'The file under validation must be an image (jpeg, png, bmp, gif, svg, or webp)',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b432',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'image',
                'rule_group' => 'Upload-File',
                'title' => 'image',
                'updated_at' => NULL,
            ),
            26 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be included in the given list of values. Since this rule often requires you to implode an array, the Rule::in method may be used to fluently construct the rule',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b433',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => 'unlimited',
                'rule' => 'in',
                'rule_group' => NULL,
                'title' => 'in:foo,bar,...',
                'updated_at' => NULL,
            ),
            27 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must exist in anotherfield\'s values.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b434',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => 'unlimited',
                'rule' => 'in_array',
                'rule_group' => NULL,
                'title' => 'in_array:anotherfield.*',
                'updated_at' => NULL,
            ),
            28 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be an integer.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b435',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'integer',
                'rule_group' => 'Number',
                'title' => 'integer',
                'updated_at' => NULL,
            ),
            29 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be less than the given field. The two fields must be of the same type. Strings, numerics, arrays, and files are evaluated using the same conventions as the size rule.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b436',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => '1',
                'rule' => 'lt',
                'rule_group' => 'Number',
                'title' => 'lt:field
',
                'updated_at' => NULL,
            ),
            30 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be less than or equal to the given field. The two fields must be of the same type. Strings, numerics, arrays, and files are evaluated using the same conventions as the size rule.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b437',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => '1',
                'rule' => 'lte',
                'rule_group' => 'Number',
                'title' => 'lte:field',
                'updated_at' => NULL,
            ),
            31 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be less than or equal to a maximum value. Strings, numerics, arrays, and files are evaluated in the same fashion as the size rule.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b438',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '1',
                'rule' => 'max',
                'rule_group' => 'Number',
                'title' => 'max:value',
                'updated_at' => NULL,
            ),
            32 =>
            array(
                'created_at' => NULL,
                'description' => 'The file under validation must match one of the given MIME types:',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b439',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => 'unlimited',
                'rule' => 'mimetypes',
                'rule_group' => 'Upload-File',
                'title' => 'mimetypes:text/plain,...',
                'updated_at' => NULL,
            ),
            33 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be a value after or equal to the given date. For more information, see the after rule.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b44',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '1',
                'rule' => 'after_or_equal',
                'rule_group' => 'Date & Time-Date-Time-Month-Day-Year',
                'title' => 'after_or_equal:date',
                'updated_at' => NULL,
            ),
            34 =>
            array(
                'created_at' => NULL,
                'description' => 'The file under validation must have a MIME type corresponding to one of the listed extensions.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b440',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => 'unlimited',
                'rule' => 'mimes',
                'rule_group' => 'Upload-File',
                'title' => 'mimes:foo,bar,...',
                'updated_at' => NULL,
            ),
            35 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must have a minimum value.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b441',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '1',
                'rule' => 'min',
                'rule_group' => 'Number',
                'title' => 'min:value',
                'updated_at' => NULL,
            ),
            36 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must not be included in the given list of values.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b442',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => 'unlimited',
                'rule' => 'not_in',
                'rule_group' => 'Text-Textarea-Email-Number-Date & Time-Date-Time-Month-Day-Year-URL',
                'title' => 'not_in:foo,bar,...',
                'updated_at' => NULL,
            ),
            37 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be numeric.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b443',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'numeric',
                'rule_group' => 'Text-Textarea-Email-Number-Date & Time-Date-Time-Month-Day-Year-URL',
                'title' => 'numeric',
                'updated_at' => NULL,
            ),
            38 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be present in the input data and not empty.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b444',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'required',
                'rule_group' => 'Text-Textarea-Email-Number-Date & Time-Date-Time-Month-Day-Year-URL-Radio-Checkbox-Select',
                'title' => 'required',
                'updated_at' => NULL,
            ),
            39 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be present and not empty if the anotherfield field is equal to any value.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b445',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => 'unlimited',
                'rule' => 'required_if',
                'rule_group' => 'All',
                'title' => 'required_if:anotherfield,value,...',
                'updated_at' => NULL,
            ),
            40 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be present and not empty unless the anotherfield field is equal to any value.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b446',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => 'unlimited',
                'rule' => 'required_unless',
                'rule_group' => 'All',
                'title' => 'required_unless:anotherfield,value,...',
                'updated_at' => NULL,
            ),
            41 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be present and not empty only if all of the other specified fields are present.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b447',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => 'unlimited',
                'rule' => 'required_with',
                'rule_group' => 'All',
                'title' => 'required_with:foo,bar,...',
                'updated_at' => NULL,
            ),
            42 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be present and not empty only when any of the other specified fields are not present.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b448',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => 'unlimited',
                'rule' => 'required_without',
                'rule_group' => 'All',
                'title' => 'required_without:foo,bar,...',
                'updated_at' => NULL,
            ),
            43 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be present and not empty only when all of the other specified fields are not present.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b449',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => 'unlimited',
                'rule' => 'required_without_all',
                'rule_group' => 'All',
                'title' => 'required_without_all:foo,bar,...',
                'updated_at' => NULL,
            ),
            44 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be entirely alphabetic characters.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b45',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'alpha',
                'rule_group' => 'Text-Textarea',
                'title' => 'Alphabetic characters only',
                'updated_at' => NULL,
            ),
            45 =>
            array(
                'created_at' => NULL,
                'description' => 'The given field must match the field under validation.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b450',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 1,
                'num_params' => '1',
                'rule' => 'same',
                'rule_group' => 'Text-Textarea-Email-Number-Date & Time-Date-Time-Month-Day-Year-URL',
                'title' => 'same:field',
                'updated_at' => NULL,
            ),
            46 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must have a size matching the given value. For string data, value corresponds to the number of characters. For numeric data, value corresponds to a given integer value (the attribute must also have the numeric or integer rule). For an array, size corresponds to the count of the array. For files, size corresponds to the file size in kilobytes.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b451',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '1',
                'rule' => 'size',
                'rule_group' => 'All',
                'title' => 'size:value',
                'updated_at' => NULL,
            ),
            47 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must start with one of the given values.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b452',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => 'unlimited',
                'rule' => 'starts_with',
                'rule_group' => NULL,
                'title' => 'starts_with:foo,bar,...',
                'updated_at' => NULL,
            ),
            48 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be a string. If you would like to allow the field to also be null, you should assign the nullable rule to the field.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b453',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'string',
                'rule_group' => 'Text-Textarea-Email-Number-Date & Time-Date-Time-Month-Day-Year-URL',
                'title' => 'string',
                'updated_at' => NULL,
            ),
            49 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must not exist within the given database table.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b454',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '4',
                'rule' => 'unique',
                'rule_group' => 'Text-Textarea-Email',
                'title' => 'unique:table,column,except,idColumn',
                'updated_at' => NULL,
            ),
            50 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be a valid URL.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b455',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'url',
                'rule_group' => 'URL',
                'title' => 'url',
                'updated_at' => NULL,
            ),
            51 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation may have alpha-numeric characters, as well as dashes and underscores.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b46',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'alpha_dash',
                'rule_group' => 'Text-Textarea-Email',
                'title' => 'alpha-numeric characters, dashes and underscores',
                'updated_at' => NULL,
            ),
            52 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be entirely alpha-numeric characters.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b47',
                'is_active' => 1,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'alpha_num',
                'rule_group' => 'Text-Textarea-Email',
                'title' => 'alpha-numeric characters only',
                'updated_at' => NULL,
            ),
            53 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be a PHP array.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b48',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'array',
                'rule_group' => 'Radio-Checkbox-Select-Dropdown',
                'title' => 'array',
                'updated_at' => NULL,
            ),
            54 =>
            array(
                'created_at' => NULL,
                'description' => 'Stop running validation rules after the first validation failure.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b49',
                'is_active' => 0,
                'is_range' => 0,
                'is_related_to_other_field' => 0,
                'num_params' => '0',
                'rule' => 'bail',
                'rule_group' => NULL,
                'title' => 'bail',
                'updated_at' => NULL,
            ),
            55 =>
            array(
                'created_at' => NULL,
                'description' => 'The field under validation must be numeric and must have a range between the given min and max.',
                'id' => '3079dd70-9106-4f08-8e77-491ecf16b50',
                'is_active' => 1,
                'is_range' => 1,
                'is_related_to_other_field' => 0,
                'num_params' => '2',
                'rule' => 'in_range',
                'rule_group' => 'Number',
                'title' => 'in_range:min,max',
                'updated_at' => NULL,
            ),
        ));
    }
}
